name: build
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: xdebug
          extensions: curl, mbstring, simplexml
      - name: Check environment
        run: |
          php --version
          composer --version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Run tests
        env:
          FREEMOBILE_PASSWORD: ${{secrets.FREEMOBILE_PASSWORD}}
          FREEMOBILE_USERNAME: ${{secrets.FREEMOBILE_USERNAME}}
        run: composer run-script test
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: composer run-script coverage
